#Introduction to Python

# Variables and Data Types
* Variables are dynammically typed. No need to write data type while declaring a variable.

In [2]:
#Declaring variables

a = 123           #integer
b = 1.23          #float
c = 1 + 2j        #complex
d = "Hello World" #string
e = True          #boolean true
f =  False        #boolean false

In [3]:
#Printing the variables

print (a)
print (b)
print (c)         #Bracket for complex number
print (d)
print (e)

123
1.23
(1+2j)
Hello World
True


In [4]:
#Checking types

type(c)

complex

In [5]:
#Basic arithmetic operations

print (5 + 2)
print (5 - 2)
print (5 * 2)
print (5 / 2)
print(5//2)
print (5 % 2)     #Mod operator. Returns remainder
print (2 ** 4)    #Power

7
3
10
2.5
2
1
16


In [6]:
print (5 / 3)
print (5 // 3)    #Returns only the Integer part

1.6666666666666667
1


In [6]:
print ("The current value of a is", a)            #Concatenated using comma
print ("The current value of a is", a, "and b is", b)

The current value of a is 123
The current value of a is 123 and b is 1.23


In [7]:
print ("The current value of a is", a)               #Default blank space
print ("The current value of a is", a, sep = '...')  #Customize using separator

The current value of a is 123
The current value of a is...123


In [8]:
print ("The current value of a is", a)          #Auto newline added. If we don't need any newline, keep it blank
print ("The current value of a is", a, end = "\n\n")
print ("Hello")

The current value of a is 123
The current value of a is 123

Hello


# String

In [9]:
#String Concatenation
x = "Hi!"
y = "My name is Mrittika"
z = x + y
print (z)

Hi!My name is Mrittika


In [10]:
#Accessing String with character position number. Space is also a character
print (y[0])
print (y[5])

M
m


In [11]:
#Length of the String
print (len(x))

3


In [12]:
#Acsessing Last Character
print (y[len(y)-1])
print(y[-1])

a
a


In [13]:
#Common String Methods
s = "My name is Mrittika"

print (y.upper())   #All uppercase
print (y.lower())   #All lowercase
print (y.title())   #Title case - Every word first letter uppercase

MY NAME IS MRITTIKA
my name is mrittika
My Name Is Mrittika


In [14]:
s = "   My name is Mrittika   "
print (s.strip())   #Strips spaces from starting or ending positions
print (s.strip().title())   #Combination of multiple methods - works sequentially

My name is Mrittika
My Name Is Mrittika


In [8]:
s = "My name is Mrittika"
print (s.find("is"))    #Returns the position of 1st letter of the intended word
print (s.find("hello")) #Not in the string
print (s.find ("a"))    #Returns 1st appearence position of the intended letter

8
-1
4


In [10]:
#Membership Operator. Returns Boolean
"Mrittika" in s

True

In [12]:
#Replace method
m = "My name is Anika"
m_new = m.replace("Anika", "Mrittika")
print (m_new)

My name is Mrittika


In [18]:
#String Slicing
s = "I love watching football!"

#m[a:b] -> Return from index a up until index b (b not included)
print (s[0:5])

I lov


In [70]:
print (s[:6])
print (s[6:])

I love
 watching football!


In [20]:
print (s[-4:])

all!


# User Input

In [13]:
username = input("Enter username:")
print("Username is: " + username)

Username is: fhgf


In [14]:
print(username*3)

fhgffhgffhgf


In [23]:
num = int(input("Enter number:"))  #Take user input as string. Need to type cast to use the numbers
print (num * 2)

Enter number:4
8


# Conditional Statements

In [24]:
x = 5
y = 6

if x > y:
  print("Maximum is x")
else:
  print ("Maximum is y")

Maximum is y


In [25]:
#elif
x = 5
y = 5

if x > y:
  print("Maximum is x")
elif x == y:
  print ("x and y are equal")
else:
  print ("Maximum is y")

x and y are equal


In [26]:
#and - Both conditions need to be True
a = 200
b = 10
c = 500
if a > b and c > a:
  print("Both conditions are True")
else:
  print("Negative!!")

Both conditions are True


In [27]:
#or - Either one of the conditions = True should be enough
a = 200
b = 10
c = 500
if a > b or a > c:
  print("At least one of the conditions is True")
else:
  print("Negative!!")

At least one of the conditions is True


In [28]:
#Nested if
x = 50

if x > 10:
  print("Above ten!")
  if x > 20:
    print("and also above 20!")
  else:
    print("but not above 20!")
else:
  print("Not even above ten!")

Above ten!
and also above 20!


In [29]:
#pass statement - Can not leave any block blank. Use pass

a = 10
b = 20

if b > a:
  pass
#else:
#print("hello")


# Python Built-in Data Types

#List
* Similar to Java or C array, but not same
* Collection of elements of multiple data types
* Allows easy modification of data
* Requires more memory to store additional information about data types of each element

In [30]:
#Initializing
list = [1, 2, 3, 4, 5]
print(list)

[1, 2, 3, 4, 5]


In [16]:
mixed_list = [1, 2.5, "hello", [1, 2, 3]]
print(mixed_list[3][2])

3


In [32]:
#List Methods
print(len(list))
print(4 in list)    #Search

list[2] = "New"     #Update value
print(list)

list.append("World")    #Add new element
print(list)


5
True
[1, 2, 'New', 4, 5]
[1, 2, 'New', 4, 5, 'World']


In [33]:
list.remove("New")    #Remove element
print(list)
list.pop(1)           #Remove using index
print(list)

list2 = [16, 55]
joined_list = list + list2
print(joined_list)

[1, 2, 4, 5, 'World']
[1, 4, 5, 'World']
[1, 4, 5, 'World', 16, 55]


In [34]:
my_list = ['a', 'b', 'c', 'e', 'f', 'd']

In [35]:
#List Slicing

print (my_list[3])
print (my_list[1:3])
print (my_list[:3])
print (my_list[3:])
print (my_list[-3:])

e
['b', 'c']
['a', 'b', 'c']
['e', 'f', 'd']
['e', 'f', 'd']


In [36]:
print (my_list[0:4:2])      #index+2 everytime
print (my_list[:])          #All elements
print (my_list[::2])
print (my_list[::-1])       #Reverse order

['a', 'c']
['a', 'b', 'c', 'e', 'f', 'd']
['a', 'c', 'f']
['d', 'f', 'e', 'c', 'b', 'a']


In [37]:
#Print last 4 elements in reverse
my_list = ['a', 'b', 'c', 'd', 'e', 'f']

print (my_list[-1:-5:-1])

['f', 'e', 'd', 'c']


In [38]:
#print 2nd to 5th element reverse order
print (my_list[4:0:-1])

['e', 'd', 'c', 'b']


In [39]:
#Matrix [List of list] using list
matrix = [[1, 2, 3, 4],
          [5, 6, 7, 8]]

# |1 2 3 4|
# |5 6 7 8|

print (matrix[1][2])

7


# Tuple
* Immutable - Items can not be modified
* Collection of elements of multiple data types

In [18]:
tuple = (1, 2, 3, 4, 5)
tuple[0]

1

In [19]:
tuple[1] = "hello"

TypeError: 'tuple' object does not support item assignment

#Set
* Immutable - Items can not be modified
* Unordered - No index
* No duplicates allowed

In [20]:
set = {"apple", "banana", "cherry", "banana"}
print(set)

{'apple', 'cherry', 'banana'}


In [21]:
set.add("orange")
print(set)

set.remove("banana")
print(set)

{'apple', 'cherry', 'banana', 'orange'}
{'apple', 'cherry', 'orange'}


# Dictionary
* Values stored as key:value pair
* Mutable
* Key can be of any types but can not be a duplicate value

In [ ]:
drivers = {
    16: "Charles",
    1: "Max",
    55: "Carlos",
    "Extra": "Liam"
}

print(drivers)

In [ ]:
print(drivers["Extra"])      #Accessing elements

drivers["Extra"] = "Ollie"
print(drivers)

drivers.update({81:"Oscar"})
print(drivers)

drivers.pop("Extra")
print(drivers)

# Loops
* 2 types - while loop and for loop

In [ ]:
#while loop
i = 0
while i < 10:
    print(i)
    i = i + 1

In [ ]:
#for loop
for i in range(0, 10, 2): #ending index is exclusive
  print(i)

In [ ]:
# Iterate over the list
list = ['a', 'b', 'c', 'd', 'e']

for i in list:
  print (i)
print("------------------")
for i in range(len(list)):
  print(i)

In [ ]:
# Program to iterate through a list using indexing
list = ['a', 'b', 'c', 'd', 'e']

# iterate over the list using index
for i in range(0, len(list)):
    print("index =", i, "value =", list[i])

In [ ]:
#break statement - Out of the loop
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)
  if x == "banana":
    break

In [ ]:
#continue statement - Stop the current iteration of the loop and continue with the next
fruits = ["apple", "banana", "cherry"]
for i in fruits:
  if i == "banana":
    continue
  print(i)

In [ ]:
fruits = ["apple", "banana", "cherry"]
for i in fruits:
  if i == "banana":
    pass
  print(i)

In [ ]:
#Nested loop
num_list = [1 , 2, 3]
alphabet_list = ['a', 'b', 'c']

for number in num_list:
    print(number)
    for letter in alphabet_list:
        print(letter)

# Functions

In [ ]:
def hello_function():
  print("Hello")

hello_function()      #Global Scope

In [ ]:
#With parameter
def name_function(fname, lname):
  print(fname, " ", lname)

name_function("Anika", "Mrittika")

In [ ]:
#With return statement
def sum_numbers(number1, number2):
  result = number1+number2
  return result

x = sum_numbers(2, 3)
print (x)

In [ ]:
#Default Parameter Value
def increment(number, by=1):
    return number + 2*by

print(increment(2))
print(increment(2, 5))

# Keyword arguments
print(increment(by=1, number=2))

In [ ]:
#If the number of arguments is unknown, add a * before the parameter name. Stored as a Tuple
def print_student_list(*kids):
  print(kids)
  for x in kids:
    print (x)

print_student_list("Emil", "Tobias", "Linus")

# Numpy
* A Python library
* Used for working with arrays
* Short form of "Numerical Python"
* Aims to provide an array object that is up to 50x faster than traditional Python lists
* Provides a lot of supporting functions

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\Sohanur Rahman Shimu\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [ ]:
arr = np.array([1 , 2, 3, 2.45, "hello"])
print(arr)

print(type(arr))

[1.   2.   3.   2.45]
<class 'numpy.ndarray'>


In [4]:
print(len(arr))
print(arr.shape)    #row, column

5
(5,)


In [71]:
#Append
x = np.array([1, 2, 3, 4, 5])
y = np.append(x, [70])
print(y)
print(x)    #No change in main array

[ 1  2  3  4  5 70]
[1 2 3 4 5]


In [73]:
#Delete
x = np.array([1, 2, 3, 4, 5])
y = np.delete(x, 3)   #Delete using index
print(x)
print(y)

# print(x)             #No change in main array

[1 2 3 4 5]
[1 2 3 5]


In [47]:
#Sorting
x = np.array([7, 8, 3, 10, 5])
sorted_x = np.sort(x)
print(sorted_x)     #Ascending
print(sorted_x[3:1:-1])   #Descending - Reverse the Ascending order sorted array

print(sorted_x[::-1])

[ 3  5  7  8 10]
[8 7]
[10  8  7  5  3]


In [75]:
arr_2d = np.array([[1, 2, 3, 7, 55],
                   [4, 5, 6, 99, 10]])
print(arr_2d)

[[ 1  2  3  7 55]
 [ 4  5  6 99 10]]


In [76]:
print(len(arr_2d))
print(arr_2d.shape)     #row, column
print(arr_2d.ndim)      #Dimension

2
(2, 5)
2


In [50]:
#indexing
arr = np.array([1, 2, 3, 4])

print(arr[0])     #1st element
print(arr[-1])    #Last element

1
4


In [51]:
arr = np.array([[1,2,3,4,5],
               [6,7,8,9,10]])
print(arr)

print('4th element on 2nd row: ', arr[1, 3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
4th element on 2nd row:  9


In [9]:
#Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])

[5 6 7]
[1 2 3 4]
[5 6]
[2 4]


In [52]:
#Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

#From the second row, slice elements from index 1 to index 4 (not included)
print(arr[1, 1:4])

#From both rows, slice index 1 to index 4 (not included)
print(arr[0:2, 1:4])

[7 8 9]
[[2 3 4]
 [7 8 9]]


In [53]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])
print (arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [54]:
print(arr[:, 0])    #column
print(arr[0, :])    #row

[1 6]
[1 2 3 4 5]


In [55]:
#zero matrix
x = np.zeros(2)
print(x)

[0. 0.]


In [77]:
y = np.zeros((4,2))     #row, column
print(y)
print(y.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
(4, 2)


In [57]:
a = np.array([3, 4, 5])
b = np.array([[1,2,3],
              [4,5,6]])

print(np.sum(a))      #Summation of all elements
print(np.prod(a))     #Product of all elements

print(np.sum(b))
print(np.sum(b, axis=0))      #Column-wise
print(np.sum(b, axis=1))      #Row-wise

12
60
21
[5 7 9]
[ 6 15]


In [59]:
#Logical indexing - Identify which elements fulfill the constraint
b = np.array([[1,2,3],[4,5,6]])
print(b > 2)

[[False False  True]
 [ True  True  True]]


In [60]:
print(b[ b > 2 ])       #Extract the elements that fulfill the constraint

[3 4 5 6]


In [61]:
b[ b > 2 ] = 100      #Replace where the constraints are fulfilled
print(b)

[[  1   2 100]
 [100 100 100]]


In [ ]:
#Iterating
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

In [ ]:
#Print row by row
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
for x in arr:
  print(x)

In [ ]:
#Print element by element
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

In [83]:
#linspace - Create a random array, same difference between the numbers
x = np.linspace(0, 100, 4)     #start, end, how many numbers
print(x)

[  0.          33.33333333  66.66666667 100.        ]


In [10]:
x = np.linspace(0, 10, 9)     #No 9 integer values of same difference between 0 - 10
print(x)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [67]:
#Element wise operation - same operation on every element at a time

print(x + 10)

[10.   11.25 12.5  13.75 15.   16.25 17.5  18.75 20.  ]


In [68]:
y = np.array([1, 2, 3, 4])
z = np.array([10, 10, 20, 30])

print(y ** 2)
print(2*y + z)

[ 1  4  9 16]
[12 14 26 38]


# Pandas
* A Python library
* Used to analyze and manipulate data

# Data Analysis

In [3]:
pip install pandas

  Using cached pytz-2025.1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB 435.7 kB/s eta 0:00:27
   ---------------------------------------- 0.1/11.6 MB 491.5 kB/s eta 0:00:24
   ---------------------------------------- 0.1/11.6 MB 717.5 kB/s eta 0:00:17
    --------------------------------------- 0.3/11.6 MB 1.1 MB/s eta 0:00:11
   - -------------------------------------- 0.4/11.6 MB 1.6 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/11.6 MB 2.7 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/11.6 MB 3.2 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/11.6 MB 3.9 MB/s eta 0:00:03
   ------- -------------------------------- 2.3/11.6 MB 5.0 MB/s eta 0:00:02
   ----------- -------------


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\Sohanur Rahman Shimu\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [4]:
import pandas as pd

In [5]:
data = {
  "Name": ['Arif', 'Nafis', 'Hasan'],
  "Age": [35, 30, 40]
}

#load data into a DataFrame [Formated data; 2 Dimensional Data Structure]
df = pd.DataFrame(data)

print(df)


    Name  Age
0   Arif   35
1  Nafis   30
2  Hasan   40


In [ ]:
#loc attribute - accessing the dataframe values
print(df.loc[0])

In [ ]:
#Read csv
df = pd.read_csv('lab1_data.csv')
print (df)          #Show first 5 and last 5 entries

In [ ]:
print (df.to_string())        #Show all entries

In [ ]:
#Analyzing data
print(df.head(10))        #Show first N entries

In [ ]:
print(df.tail())          #Show last 5 entries

In [ ]:
print(df.info())          #Information summary of all datas

In [ ]:
print(df.describe())        #More detailed information of all datas

In [ ]:
#Information of a specific column
print(df["Calories"].mean())
print(df["Calories"].median())
print(df["Calories"].mode())

#Data Cleaning

In [8]:
#Drop rows with empty cells. Return a new Data Frame.
new_df = df.dropna()
print(new_df.to_string())

    Name  Age
0   Arif   35
1  Nafis   30
2  Hasan   40


In [9]:
#Replace NULL values with the mean value = 375
df.fillna(375, inplace = True)        #Inplace - Changes saved in the same Dataframe
print(df.to_string())

    Name  Age
0   Arif   35
1  Nafis   30
2  Hasan   40


In [10]:
#Update data
df.loc[5, 'Pulse'] = 45

print(df.to_string())

    Name   Age  Pulse
0   Arif  35.0    NaN
1  Nafis  30.0    NaN
2  Hasan  40.0    NaN
5    NaN   NaN   45.0


In [11]:
#Duplicate data finding
print(df.duplicated().to_string())      #False - Unique, True - Duplicate values

0    False
1    False
2    False
5    False


In [12]:
#Drop duplicate data
df.drop_duplicates(inplace = True)
print(df.duplicated().to_string())

0    False
1    False
2    False
5    False


In [13]:
#correlation
df.corr()       # 0 - No relation, 1 - Strongly correlated, -1 - Strongly correlated but adversely

ValueError: could not convert string to float: 'Arif'

#Data Visualisation

In [7]:
#plot data
df.plot()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [14]:
#Customise to make it more understandable
df.plot(kind = 'scatter', x = 'Duration', y = 'Calories')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [15]:
df.plot(kind = 'scatter', x = 'Duration', y = 'Maxpulse')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [ ]:
df["Duration"].plot(kind = 'hist')